---
trust-domain: adhoc

task-priority: high
# XXX once I figure out how to fix this
#    by-level:
#        3: very-high
#        1: very-low

taskgraph:
    register: adhoc_taskgraph:register
    repositories:
        adhoc-signing:
            name: "Adhoc Signing"
            project-regex: adhoc-signing$
            default-repository: https://github.com/mozilla-releng/adhoc-signing
            default-ref: master
            type: git
        staging-adhoc-signing:
            # string: the name of the repo, for humans
            name: "Staging Adhoc Signing"
            project-regex: staging-adhoc-signing$
            default-repository: https://github.com/mozilla-releng/staging-adhoc-signing
            default-ref: master
            type: git
    cached-task-prefix: adhoc-signing

workers:
    aliases:
        b-linux:
            provisioner: adhoc-{level}
            implementation: docker-worker
            os: linux
            worker-type: 'b-linux'
        images:
            provisioner: adhoc-{level}
            implementation: docker-worker
            os: linux
            worker-type: 'images'
        dep-signing:
            provisioner: scriptworker-k8s
            implementation: scriptworker-signing
            os: scriptworker
            worker-type: adhoc-t-signing
        signing:
            provisioner: scriptworker-k8s
            implementation: scriptworker-signing
            os: scriptworker
            worker-type:
                by-level:
                    "3": adhoc-3-signing
                    default: adhoc-t-signing
        mac-signing:
            provisioner: scriptworker-prov-v1
            implementation: scriptworker-signing
            os: macosx
            # We don't need a separate worker type
            # for level 1 because RelEng are the only
            # people who can pick off signing requests.
            # This means that there's no security benefit
            # to separating the level 1 / level 3 workers.
            worker-type: adhoc-3-mac-signing
        shipit:
            provisioner: scriptworker-k8s
            implementation: scriptworker-shipit
            os: scriptworker
            worker-type:
                by-level:
                    "3": adhoc-3-shipit
                    default: adhoc-t-shipit

notify:
    email:
        # TODO by-project/level
        - release+adhoc-signing@mozilla.com
    # TODO by-project/level
    prefix: "[adhoc]"

release-promotion:
    flavors:
        promote:
            target-tasks-method: promote_adhoc

private-artifact-prefix: releng/adhoc

scriptworker:
    scope-prefix: project:adhoc:releng
